# Generated by Django 5.2.6 on 2025-09-13 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouletteSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.IntegerField(default=10, verbose_name='Bet amount')),
                ('bet_type', models.IntegerField(choices=[(0, 'Single'), (1, 'Color')], verbose_name='Bet type')),
                ('bet_value', models.IntegerField(verbose_name='Bet value')),
                ('result_value', models.FloatField(verbose_name='Result value')),
                ('is_win', models.BooleanField(default=False, verbose_name='Is win')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Spin time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spins', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Spin',
                'verbose_name_plural': 'Spins',
                'ordering': ['-time_create'],
            },
        ),
    ]
