# Generated by Django 5.2.6 on 2025-09-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_roulettespin_result_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulettespin',
            name='win_value',
            field=models.IntegerField(null=True, verbose_name='Win value'),
        ),
    ]
